CREATE DATABASE University;
USE University;

CREATE TABLE Department(
 DeptID INT PRIMARY KEY, DeptName VARCHAR(30));

CREATE TABLE Faculty(
 FID INT PRIMARY KEY, FName VARCHAR(30), DeptID INT);

CREATE TABLE Student(
 SID INT PRIMARY KEY, SName VARCHAR(30), DeptID INT);

CREATE TABLE Course(
 CID INT PRIMARY KEY, CName VARCHAR(30), DeptID INT);

CREATE TABLE Enrollment(
 SID INT, CID INT, Marks INT);